server:
  port: 8000

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ku1593574628
    url: jdbc:mysql://localhost:3306/backhome
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    com.lsc.backhome: debug